name: Release please 🔖

on:
  workflow_run:
    workflows: ["Code quality 💎"]
    branches: [main]
    types:
      - completed

jobs:
  release-job:
    name: 🎫 Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Release with release-please
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: php
